// src/enums/booking.ts
export enum BOOKING_STATUS {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  DECLINED = 'DECLINED',
  CANCELLED = 'CANCELLED',
  COMPLETED = 'COMPLETED',
  AUTO_RELEASED = 'AUTO_RELEASED',
}

export enum PAYMENT_STATUS {
  UNPAID = 'UNPAID',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
}

export enum CANCELLED_BY {
  CLIENT = 'CLIENT',
  CAREGIVER = 'CAREGIVER',
  ADMIN = 'ADMIN',
}

export enum SHIFT_TYPE {
  MORNING = 'MORNING',
  AFTERNOON = 'AFTERNOON',
  EVENING = 'EVENING',
  NIGHT = 'NIGHT',
}