export enum DOCUMENT_TYPE {
  GOVERNMENT_ID = 'GOVERNMENT_ID',
  NURSING_CERT = 'NURSING_CERT',
  CRIMINAL_RECORD = 'CRIMINAL_RECORD',
  INSURANCE = 'INSURANCE',
}

export enum DOCUMENT_STATUS {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}